-- 코드를 입력하세요
SELECT A.CART_ID
FROM 
    (SELECT * FROM CART_PRODUCTS WHERE NAME = 'Milk' GROUP BY CART_ID) AS A
    LEFT JOIN
    (SELECT * FROM CART_PRODUCTS WHERE NAME = 'Yogurt' GROUP BY CART_ID) AS B
    ON A.CART_ID = B.CART_ID
WHERE B.CART_ID IS NOT NULL
ORDER BY A.CART_ID

# SELECT * FROM CART_PRODUCTS WHERE NAME = 'Milk'