SELECT T1.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T1 LEFT JOIN ITEM_TREE T2 ON T1.ITEM_ID = T2.PARENT_ITEM_ID
    LEFT JOIN ITEM_INFO I ON T1.ITEM_ID = I.ITEM_ID
GROUP BY T1.ITEM_ID
HAVING COUNT(T2.PARENT_ITEM_ID) = 0
ORDER BY 1 DESC














# -- 코드를 작성해주세요
# SELECT A.ITEM_ID ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO A JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
# WHERE A.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE 
#                         WHERE PARENT_ITEM_ID IS NOT NULL 
#                         GROUP BY PARENT_ITEM_ID)
# ORDER BY 1 DESC