SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY O.DATETIME - I.DATETIME DESC
LIMIT 2










# -- 코드를 입력하세요
# SELECT A.ANIMAL_ID, A.NAME
# FROM ANIMAL_INS A, ANIMAL_OUTS B
# WHERE A.ANIMAL_ID = B.ANIMAL_ID
# ORDER BY DATEDIFF(A.DATETIME, B.DATETIME) 
# LIMIT 2