SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, R.SCORE
FROM REST_INFO I 
        RIGHT JOIN (SELECT ROUND(AVG(REVIEW_SCORE), 2) AS SCORE, REST_ID
                    FROM REST_REVIEW 
                    GROUP BY REST_ID) R 
        ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, I.FAVORITES DESC














# SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO AS A JOIN REST_REVIEW AS B ON A.REST_ID = B.REST_ID
# GROUP BY REST_ID
# HAVING A.ADDRESS LIKE "서울%"
# ORDER BY SCORE DESC, A.FAVORITES DESC