SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE FROM MEMBER_PROFILE A JOIN REST_REVIEW B
    ON A.MEMBER_ID = B.MEMBER_ID
    JOIN (SELECT MEMBER_ID, COUNT(MEMBER_ID) REVIEW_COUNT FROM REST_REVIEW 
    GROUP BY MEMBER_ID) C
    ON B.MEMBER_ID = C.MEMBER_ID
    WHERE C.REVIEW_COUNT >= (SELECT COUNT(MEMBER_ID) FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1) 
    ORDER BY A.MEMBER_NAME ASC, B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC;