SELECT COUNT(*) AS FISH_COUNT, FNI.FISH_NAME
FROM FISH_INFO FI LEFT JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY FISH_NAME
ORDER BY 1 DESC










# -- 코드를 작성해주세요
# SELECT COUNT(*) AS FISH_COUNT, FN.FISH_NAME 
# FROM FISH_INFO F JOIN FISH_NAME_INFO FN
# ON F.FISH_TYPE = FN.FISH_TYPE
# GROUP BY FN.FISH_NAME
# ORDER BY 1 DESC