SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT)*P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P RIGHT JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(O.PRODUCE_DATE, "%Y-%m") LIKE "2022-05%"
GROUP BY O.PRODUCT_ID
HAVING PRODUCT_NAME IS NOT NULL
ORDER BY 3 DESC, 1











# -- 코드를 입력하세요
# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * SUM(O.AMOUNT)) AS TOTAL_SALES
# FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
# ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE O.PRODUCE_DATE LIKE '2022-05%'
# GROUP BY P.PRODUCT_ID
# ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID