-- 코드를 입력하세요
# WITH AP AS (SELECT * FROM APPOINTMENT A LEFT JOIN PATIENT P ON A.PT_NO = P.PT_NO)

SELECT AP.APNT_NO, AP.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM  (SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, A.MDDR_ID, A.APNT_YMD, A.APNT_CNCL_YN
       FROM APPOINTMENT A LEFT JOIN PATIENT P ON A.PT_NO = P.PT_NO) AS AP 
        LEFT JOIN DOCTOR D ON AP.MDDR_ID = D.DR_ID
WHERE AP.APNT_YMD LIKE "2022-04-13%" AND AP.APNT_CNCL_YN = 'N' AND AP.MCDP_CD = "CS"
ORDER BY AP.APNT_YMD