SELECT DATE_FORMAT(DATETIME, "%H") AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, "%H") > 8 AND DATE_FORMAT(DATETIME, "%H") < 20
GROUP BY DATE_FORMAT(DATETIME, "%H")
ORDER BY 1










# -- 코드를 입력하세요
# SELECT HOUR(DATETIME), COUNT(*) AS COUNT
# FROM ANIMAL_OUTS
# WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR(DATETIME)