-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) YEAR, (B.SIZE-A.SIZE_OF_COLONY) YEAR_DEV, ID
FROM ECOLI_DATA A LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) SIZE
                            FROM ECOLI_DATA
                            GROUP BY YEAR) B
ON YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV