SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO I LEFT JOIN FISH_NAME_INFO NI ON I.FISH_TYPE = NI.FISH_TYPE
WHERE NI.FISH_NAME IN ("BASS", "SNAPPER")










# -- 코드를 작성해주세요
# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO
# WHERE FISH_TYPE IN (SELECT A.FISH_TYPE 
#                     FROM FISH_INFO A JOIN FISH_NAME_INFO B 
#                     ON A.FISH_TYPE = B.FISH_TYPE 
#                     WHERE B.FISH_NAME IN ('BASS', 'SNAPPER'))