SELECT B.CATEGORY AS CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS BS JOIN BOOK AS B
ON BS.BOOK_ID = B.BOOK_ID
WHERE BS.SALES_DATE LIKE "2022-01-%"
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY










# -- 코드를 입력하세요
# SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
# FROM BOOK A
# RIGHT JOIN BOOK_SALES B
# ON A.BOOK_ID = B.BOOK_ID
# WHERE B.SALES_DATE LIKE "2022-01-%"
# GROUP BY A.CATEGORY
# ORDER BY A.CATEGORY