SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d") AS DATE_FORMAT
FROM BOOK AS B LEFT JOIN AUTHOR AS A 
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY LIKE '경제'
ORDER BY PUBLISHED_DATE










# SELECT a.BOOK_ID, b.AUTHOR_NAME, date_format(a.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
# FROM BOOK a JOIN AUTHOR b on a.AUTHOR_ID = b.AUTHOR_ID
# WHERE CATEGORY LIKE '경제' 
# ORDER BY PUBLISHED_DATE